# Site settings
title: JD Eames
description: storyteller
baseurl:   # #
url:  https://www.jdeames.com # the base hostname & protocol for your site #


twitter_username:     PeaceableWriter
github_username:      jdeames
instagram_username:   peaceablewriter
wordpress_username:   PeaceableWriter
vimeo_username:       PeaceableWriter

# Build settings
markdown: kramdown


permalink: pretty
relative: true



