# Site settings
title: JD Eames
decription: all things
baseurl:   # #
url:  http://www.jdeames.com # the base hostname & protocol for your site #


twitter_username:     PeaceableWriter
github_username:      jdeames
instagram_username:   jdePW
wordpress_username:   PeaceableWriter
vimeo_username:       GuerrillaDaVille

# Build settings
markdown: redcarpet
highlighter: pygments

# Pagination
paginate: 7
paginate_path: "/news/page:num/"

collections:
  stories:
    output: true
    permalink: /stories/:path/
  news:
    output: true
    permalink: /news/:path/
    


