# Site settings
title: JD Eames
decription: all things
baseurl:   # #
url:  http://www.jdeames.com # the base hostname & protocol for your site #
twitter_username:     PeaceableWriter
github_username:      jdeames
instagram_username:   jdePW
wordpress_username:   PeaceableWriter
vimeo_username:       GuerrillaDaVille
vine_username:		  PeaceableWriter

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

# Pagination
paginate: 7
paginate_path: "/news/page:num/"

collections:
  stories:
    output: true
    permalink: /stories/:path/
  news:
    output: true
    permalink: /news/:path/


