title: JD Eames
description: > # this means to ignore newlines until "baseurl:"
  website for all things JD Eames, Storyteller
# permalink: ':title/' 
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.jdeames.com # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: JD Eames # add your name
author-img: jde.jpg # add your photo
about-author: I write stories
author-pronouns: she/her
social-twitter: peaceablewriter
social-instagram: peaceablewriter
social-wordpress: peaceablewriter
social-instagram: peaceablewriter
social-email: julie@jdeames.com
social-vimeo: peaceablewriter


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
include: ['_excerpts']
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
collections:
  tags:
    output: true
    permalink: tags/:path/
