# Site settings
title: JD Eames
description: all things
baseurl:   # #
url:  http://www.jdeames.com # the base hostname & protocol for your site #


twitter_username:     PeaceableWriter
github_username:      jdeames
instagram_username:   jdePW
wordpress_username:   PeaceableWriter
vimeo_username:       GuerrillaDaVille

# Build settings
markdown: kramdown


permalink: pretty
relative: true



