title: JD Eames
description: Storyteller
# permalink: ':title/' 
baseurl: ##
url: https://www.jdeames.com # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: JD Eames # add your name
author-img: jde.jpg # add your photo
about-author: I write stories
author-pronouns: she/her
social-twitter: peaceablewriter
social-instagram: peaceablewriter
social-wordpress: peaceablewriter
social-instagram: peaceablewriter
social-email: julie@jdeames.com
social-vimeo: peaceablewriter


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate


paginate: 8
paginate_path: "/page/:num"
include: ['_excerpts']

