# Site settings
title: JD Eames
ititle: JD
lang: en
description: storyteller
baseurl:   # #
url:  https://www.jdeames.com # the base hostname & protocol for your site #

twitter_username:     PeaceableWriter
instagram_username:   PeaceableWriter
wordpress_username:   PeaceableWriter
vimeo_username:       PeaceableWriter

# Build settings
markdown: kramdown
